name: Build RSS Feed

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Generate RSS snippet
        run: python scripts/fetch_rss.py
