name: Deploy to Neocities

on:
  push:
    branches:
      - main 
      
concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install curl

      - name: Deploy to Neocities
        run: |
          curl -F "index.html=@index.html" \
               -F "api_key=${{ secrets.NEOCITIES_API_KEY }}" \
               https://neocities.org/api/upload
      
          find images -type f -print0 | while IFS= read -r -d '' file; do
            echo "Uploading $file"
            curl -F "${file}=@${file}" \
                 -F "api_key=${{ secrets.NEOCITIES_API_KEY }}" \
                 https://neocities.org/api/upload
          done
